name: docs-build-action
description: Build documentation

inputs:
  revision:
    default: "default_revision"
  src-root:
    default: "./"
  lint-root:
    default: "./_docs-lint"
  build-root:
    default: "./_docs-build"
  cli-version:  
    default: "latest"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm i @diplodoc/cli@${{ inputs.cli-version }} -g --save-exact
      shell: bash

    - name: Need pdf generation
      id: get-pdf-params
      run: |
        if [[ -e "${{ inputs.src-root }}/.yfm" ]]; then
          need_pdf=$(yq -r '.docs-viewer.pdf // false' < ${{ inputs.src-root }}/.yfm)
        else
          need_pdf=false
        fi

        pdf_args=''

        if [[ "$need_pdf" == 'true' ]]; then
          pdf_args='--single-page'
        fi

        echo "need_pdf=$need_pdf" >> $GITHUB_OUTPUT
        echo "pdf_args=$pdf_args" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build md2html
      id: build-md2html
      run: |
        set +e
        set -o pipefail

        yfm -i ${{ inputs.src-root }} -o ${{ inputs.lint-root }} ${{ steps.get-pdf-params.outputs.pdf_args }} 2>&1 | tee './build-html.log'

        echo "exitcode=$?" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build md2md
      id: build-md2md
      run: |
        set +e
        set -o pipefail

        yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }} --output-format md --add-map-file --allow-custom-resources 2>&1 | tee './build-md.log'

        echo "exitcode=$?" >> $GITHUB_OUTPUT

      shell: bash

    - name: Run docs2pdf
      if: steps.get-pdf-params.outputs.need_pdf == 'true'
      shell: bash
      run: |
        set +e
        set -o pipefail

        sudo apt-get update
        sudo apt-get install fonts-arphic-ukai
        sudo apt-get install fonts-arphic-uming
        sudo apt-get install fonts-noto-cjk

        npx -y -- @diplodoc/pdf-generator@latest -i ${{ inputs.lint-root }}

        rsync -r --include='*.pdf' --include='*/' --exclude='*' ${{ inputs.lint-root }}/ ${{ inputs.build-root }}/

    - name: Save inputs
      run: |
        mkdir -p ./inputs
        echo ${{ inputs.revision }} > ./inputs/revision
        echo ${{ github.event.number }} > ./inputs/pr-number
      shell: bash
    - name: Upload inputs
      uses: actions/upload-artifact@v4
      with:
        name: inputs
        path: inputs/
        include-hidden-files: true
        retention-days: 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-md
        include-hidden-files: true
        path: ${{ inputs.build-root }}
        retention-days: 1
    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log-html
        path: ./build-html.log
        retention-days: 1
    - name: Exit
      run: |
        exitcode=${{ steps.build-md2html.outputs.exitcode }}

        if [ "$exitcode" -eq 0 ]; then
            echo "Build exited successfully."
        else
          echo "Build exited with an error. Exit code: $exitcode"
          exit $exitcode
        fi
      shell: bash
