name: docs-build-action
description: Build & Upload Docs

inputs:
  revision:
    required: true
  project-name:
    required: true
  src-root:
    required: true
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  lint-root:
    default: "./_docs-lint"
  build-root:
    default: "./_docs-build"
  shared-storage-bucket:
    default: false
    type: boolean

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm i @doc-tools/docs -g
      shell: bash
    - run: yfm -i ${{ inputs.src-root }} -o ${{ inputs.lint-root }}
      shell: bash
    - name: build
      run: |
        yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }} --output-format md --add-map-file --allow-custom-resources
      shell: bash
    - name: Set DEST_DIR
      shell: bash
      run: |
        if [ "${{ inputs.shared-storage-bucket }}" == "true" ]; then
          echo "DEST_DIR=${{ inputs.project-name }}/rev/${{ inputs.revision }}" >> $GITHUB_ENV
        else
          echo "DEST_DIR=rev/${{ inputs.revision }}" >> $GITHUB_ENV
        fi
    - name: Upload S3
      shell: bash
      run: |
        yfm publish \
          -i ${{ inputs.build-root }} \
          --endpoint ${{ inputs.storage-endpoint }} \
          --region ${{ inputs.storage-region }} \
          --bucket ${{ inputs.storage-bucket }} \
          --prefix ${{ env.DEST_DIR }} \
          --access-key-id ${{ inputs.storage-access-key-id }} \
          --secret-access-key ${{ inputs.storage-secret-access-key }}
