name: docs-build-action
description: Build & Upload Docs

inputs:
  revision:
    required: true
  project-name:
    required: true
  src-root:
    required: true
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  lint-root:
    default: "./_docs-lint"
  build-root:
    default: "./_docs-build"
  shared-storage-bucket:
    default: false

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm i @doc-tools/docs -g
      shell: bash
    - run: yfm -i ${{ inputs.src-root }} -o ${{ inputs.lint-root }}
      shell: bash
    - name: build
      run: |
        yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }} --output-format md --add-map-file --allow-custom-resources
      shell: bash
    - name: Upload S3
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --exact-timestamps
      env:
        DEST_DIR: "${{ inputs.shared-storage-bucket == 'true' && inputs.project-name + "/" }}rev/${{ inputs.revision }}"
        SOURCE_DIR: "${{ inputs.build-root }}"
        AWS_S3_BUCKET: ${{ inputs.storage-bucket }}
        AWS_S3_ENDPOINT: ${{ inputs.storage-endpoint }}
        AWS_ACCESS_KEY_ID: ${{ inputs.storage-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.storage-secret-access-key }}
        AWS_REGION: ${{ inputs.storage-region }}
